'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),factory=require('../lib/faborn-ui');
function setup(){const values={},marks={},favorites={};let profile=0;const L={Storage:{get:(k,f)=>values[k]??f,set:(k,v)=>values[k]=v},Utils:{hash:s=>s},Timeline:{filename:()=>profile?'file_view_'+profile:'file_view',view:k=>(marks[profile+'|'+k]||{})},Favorite:{check:m=>favorites[m.id]||{}}};const ui=factory({},L,null);return {ui,values,marks,favorites,profile:p=>profile=p,put:(k,v)=>marks[profile+'|'+k]=v};}
const movie={id:872585,original_title:'Oppenheimer',title:'Оппенгеймер',release_date:'2023-07-19'},tv={id:136311,original_name:'Shrinking',name:'Правдива терапія',first_air_date:'2023-01-27'};
test('manual viewed films use a complete accessible state and never truncated text',()=>{const {ui,favorites}=setup();favorites[movie.id]={viewed:true};assert.deepEqual(ui.posterProgress(movie),{label:'',detail:'Переглянуто',done:true,percent:100,newSeason:0});});
test('library watched films are marked on posters at 80 percent and without a native favorite',()=>{
 const {ui,values,put,profile}=setup();values.faborn_ukr_my_movies_v1_file_view=[{...movie,libraryState:'watched'}];
 assert.equal(ui.posterProgress(movie).done,true);put('Oppenheimer',{percent:80,time:800,updated:10});assert.equal(ui.posterProgress(movie).done,true);
 profile(1);assert.equal(ui.posterProgress(movie).detail,'');profile(0);values.faborn_ukr_my_movies_v1_file_view[0].libraryState='wanted';assert.equal(ui.posterProgress(movie).done,false);
 values.faborn_ukr_my_movies_v1_file_view=[];assert.equal(ui.posterProgress(movie).done,false);
});
test('movie library cannot mark an unrelated source, series or invalid storage as watched',()=>{
 const {ui,values}=setup();for(const rows of [{},null,[null],[{...movie,libraryState:'wanted'}],[{...movie,source:'other',libraryState:'watched'}],[{...movie,media_type:'tv',libraryState:'watched'}],[{...movie,id:136311,libraryState:'watched'}]]){
  values.faborn_ukr_my_movies_v1_file_view=rows;assert.equal(ui.posterProgress(movie).detail,'');assert.equal(ui.posterProgress(tv).detail,'');
 }
});
test('TV last episode follows actual latest timeline update across online and torrent keys',()=>{const {ui,put}=setup();ui.rememberEpisode('tmdb-tv-136311',{season:2,episode:7});put('faborn|tmdb-tv-136311|2|7',{percent:100,time:1700,updated:10});let p=ui.posterProgress(tv);assert.equal(p.label,'S2 · E7');assert.equal(p.done,true);put('27Shrinking',{percent:30,time:510,updated:20});p=ui.posterProgress(tv);assert.equal(p.done,false);assert.equal(p.percent,30);assert.equal(p.detail,'Продовжити: сезон 2, серія 7');});
test('episode index stores identity only and cannot leak watched state into another profile',()=>{const {ui,put,profile,values}=setup();ui.rememberEpisode('tmdb-tv-136311',{season:2,episode:7,url:'secret'});put('faborn|tmdb-tv-136311|2|7',{percent:95,updated:10});assert.equal(ui.posterProgress(tv).done,true);profile(1);assert.equal(ui.posterProgress(tv).detail,'');assert.ok(!JSON.stringify(values).includes('secret'));});
test('reset progress wins over an older completed mark',()=>{const {ui,put}=setup();ui.rememberEpisode('tmdb-tv-136311',{season:2,episode:7});put('faborn|tmdb-tv-136311|2|7',{percent:100,updated:10});put('27Shrinking',{percent:0,updated:20});assert.equal(ui.posterProgress(tv).detail,'');});
test('legacy last position needs a matching profile timeline and cannot invent progress',()=>{const {ui,values,put}=setup();values.faborn_ukr_position_tmdb_tv_136311={season:2,episode:7,percent:99};values['faborn_ukr_position_tmdb-tv-136311']={season:2,episode:7,percent:99};assert.equal(ui.posterProgress(tv).detail,'');put('27Shrinking',{percent:99,updated:15});assert.equal(ui.posterProgress(tv).label,'S2 · E7');});
test('native watched episodes from later seasons are found from verified metadata',()=>{const {ui,put}=setup();ui.rememberSeasons({...tv,seasons:[{season_number:11,episode_count:2,air_date:'2020-01-01'}]});put('11:2Shrinking',{percent:95,updated:20});assert.equal(ui.posterProgress(tv).label,'S11 · E2');});
test('new season requires a dated released episode and excludes future/undated/special seasons',()=>{const {ui,put}=setup();const seasons=[{season_number:0,episode_count:1,air_date:'2024-01-01'},{season_number:3,episode_count:1,air_date:'2025-01-01'},{season_number:4,episode_count:1,air_date:'2099-01-01'},{season_number:5,episode_count:0,air_date:'2025-01-01'},{season_number:6,episode_count:1,air_date:null}];assert.equal(ui.releasedSeason(seasons,2,Date.parse('2026-10-01')),3);assert.equal(ui.releasedSeason(seasons,3,Date.parse('2026-10-01')),0);ui.rememberSeasons({...tv,seasons});ui.rememberEpisode('tmdb-tv-136311',{season:2,episode:7});put('27Shrinking',{percent:100});assert.equal(ui.posterProgress(tv).newSeason,3);});
test('poster qualities keep online/torrent provenance separate and disappear when unavailable or expired',()=>{const {ui,values}=setup();assert.equal(ui.posterQualities(movie),'');ui.learn(movie,{qualities:['1080p'],languages:['uk']});ui.learnTorrents(movie,{Results:[{Title:'Oppenheimer (2023) 2160p [ENG]'}]});const html=ui.posterQualities(movie);assert.match(html,/Онлайн: Full HD · UA/);assert.match(html,/Торрент: 4K · EN/);assert.ok(!html.includes('HDR'));values.faborn_ukr_badges='off';assert.equal(ui.posterQualities(movie),'');});
test('next partially visible card becomes the first card of the new page',()=>{const {ui}=setup();for(let i=0;i<6;i++)assert.equal(ui.pageStart(i,0,6),0);assert.equal(ui.pageStart(6,0,6),6);assert.equal(ui.pageStart(7,6,6),6);assert.equal(ui.pageStart(5,6,6),0);assert.equal(ui.pageStart(2,0,2),2);});
test('initial focus repairs a competing plugin but stops immediately after user navigation',()=>{const {ui}=setup();const button={classList:{contains:()=>false},offsetParent:true},record={initialFocus:true,start:{last:'competitor'},node:{querySelector:()=>button}};ui.preferFabornFocus(record,true);assert.equal(record.start.last,button);ui.endInitialFocus(record);record.start.last='user choice';ui.preferFabornFocus(record,true);assert.equal(record.start.last,'user choice');});
